// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWL0pDEaF1Zrb8AAn90I23gzDnRJo5nns',
    appId: '1:503131870075:web:232a0d859ec54f8cf3a3de',
    messagingSenderId: '503131870075',
    projectId: 'cicd-9a368',
    authDomain: 'cicd-9a368.firebaseapp.com',
    storageBucket: 'cicd-9a368.firebasestorage.app',
    measurementId: 'G-3EN2TWZ8J9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZz2JSS8JcyIbyDt2Q3PfHHsWDEQ380jU',
    appId: '1:503131870075:android:22ec19c403b78c43f3a3de',
    messagingSenderId: '503131870075',
    projectId: 'cicd-9a368',
    storageBucket: 'cicd-9a368.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB70WpLw-BImNPYstSfUd2V1q7qxaNR1UA',
    appId: '1:503131870075:ios:b969b960d7377444f3a3de',
    messagingSenderId: '503131870075',
    projectId: 'cicd-9a368',
    storageBucket: 'cicd-9a368.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB70WpLw-BImNPYstSfUd2V1q7qxaNR1UA',
    appId: '1:503131870075:ios:b969b960d7377444f3a3de',
    messagingSenderId: '503131870075',
    projectId: 'cicd-9a368',
    storageBucket: 'cicd-9a368.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWL0pDEaF1Zrb8AAn90I23gzDnRJo5nns',
    appId: '1:503131870075:web:88ad071ef8f592dff3a3de',
    messagingSenderId: '503131870075',
    projectId: 'cicd-9a368',
    authDomain: 'cicd-9a368.firebaseapp.com',
    storageBucket: 'cicd-9a368.firebasestorage.app',
    measurementId: 'G-R8W7VJ4W9H',
  );
}
